services:
  web:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "8088:80"   # truy cập http://localhost:8080
    volumes:
      - ./html:/usr/share/nginx/html:ro 
    
    restart: always
